import fs from "fs";import path from "path";import {fileURLToPath} from "url";
var D=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../public/data");
function p(a){return a[Math.floor(Math.random()*a.length)]}
function pn(a,n){var s=new Set();while(s.size<n&&s.size<a.length)s.add(p(a));return[...s]}
var df=["easy","medium","hard"];
var ts="microservice monolithic service split service boundary domain driven design DDD service registration service discovery Nacos Eureka config center config refresh multi-environment OpenFeign REST RPC load balancing Ribbon Spring Cloud LoadBalancer circuit breaker rate limiting degradation Sentinel Hystrix API Gateway Spring Cloud Gateway route predicate filter auth JWT OAuth2 unified auth trace TraceId Zipkin SkyWalking log aggregation ELK distributed transaction Seata AT TCC Saga eventual consistency message queue idempotent Docker Kubernetes grayscale release blue-green release microservice governance context boundary aggregate repository domain event CQRS event sourcing saga pattern orchestrator choreography anti-corruption layer sidecar service mesh istio envoy API composition BFF backend for frontend contract testing consumer-driven contract microservice deployment container orchestration health check canary release feature flag";
var t=ts.trim().split(/\s+/).filter(Boolean);
function bt(){return t.map(function(n,i){return{id:"ms-tag-"+String(i+1).padStart(3,"0"),name:n,category:"MicroSvc",description:"MS标签:"+n,count:0,createdAt:"2026-07-03T00:00:00.000Z"};});}
var CD=[
  {id:"ms-course-01",order:1,slug:"MS入门",title:"微服务架构入门与演进路线",description:"微服务定义、与单体对比、学习路线。",estimatedHours:4,diff:"easy"},
  {id:"ms-course-02",order:2,slug:"拆分边界",title:"单体架构拆分与服务边界设计",description:"拆分原则、服务边界、DDD入门、限界上下文。",estimatedHours:10,diff:"medium"},
  {id:"ms-course-03",order:3,slug:"SpringCloud生态",title:"Spring Cloud生态基础",description:"Spring Cloud组件、版本、项目结构。",estimatedHours:6,diff:"medium"},
  {id:"ms-course-04",order:4,slug:"注册发现",title:"服务注册与发现：Nacos / Eureka",description:"注册中心原理、Nacos安装、服务注册发现。",estimatedHours:10,diff:"medium"},
  {id:"ms-course-05",order:5,slug:"配置中心",title:"配置中心与多环境配置",description:"Nacos配置中心、配置热更新、多环境切换。",estimatedHours:8,diff:"hard"},
  {id:"ms-course-06",order:6,slug:"服务调用",title:"服务调用：OpenFeign与REST",description:"OpenFeign声明式调用、超时、重试、日志。",estimatedHours:8,diff:"hard"},
  {id:"ms-course-07",order:7,slug:"负载均衡",title:"负载均衡与服务容错",description:"Ribbon/LoadBalancer、轮询权重、容错机制。",estimatedHours:8,diff:"hard"},
  {id:"ms-course-08",order:8,slug:"API网关",title:"API网关：Spring Cloud Gateway",description:"Gateway路由、断言工厂、过滤器链、鉴权。",estimatedHours:10,diff:"hard"},
  {id:"ms-course-09",order:9,slug:"熔断限流",title:"熔断、限流与降级：Sentinel",description:"Sentinel流控、熔断降级、热点、系统规则。",estimatedHours:10,diff:"hard"},
  {id:"ms-course-10",order:10,slug:"链路追踪",title:"链路追踪、日志与可观测性",description:"TraceId传播、Zipkin/SkyWalking、ELK。",estimatedHours:8,diff:"hard"},
  {id:"ms-course-11",order:11,slug:"分布式事务",title:"分布式事务：Seata与最终一致性",description:"Seata AT/TCC/Saga模式、XA、消息一致性。",estimatedHours:10,diff:"hard"},
  {id:"ms-course-12",order:12,slug:"认证授权",title:"认证授权、JWT与统一鉴权",description:"JWT令牌、OAuth2入门、Gateway统一鉴权。",estimatedHours:8,diff:"hard"},
  {id:"ms-course-13",order:13,slug:"容器化部署",title:"Docker、Kubernetes与微服务部署",description:"Docker镜像、K8s部署、灰度发布、健康检查。",estimatedHours:10,diff:"hard"},
  {id:"ms-course-14",order:14,slug:"MS项目面试",title:"微服务综合项目、面试与架构训练",description:"完整项目整合、面试题、架构演进。",estimatedHours:10,diff:"hard"},
];
function bc(){return CD.map(function(c){return{id:c.id,order:c.order,slug:c.slug,title:c.title,description:c.description,estimatedHours:c.estimatedHours,difficulty:c.diff,tags:[c.title],lessonIds:[],totalLessons:0,totalQuestions:0,prerequisites:[],outcomes:["理解微服务架构","掌握Spring Cloud","能进行服务治理","完成微服务项目"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bl(){var all=[];var id=1;function add(ci,t2){var n=String(id).padStart(3,"0");all.push({id:"ms-lesson-"+n,courseId:CD[ci].id,order:all.filter(function(l){return l.courseId===CD[ci].id}).length+1,title:t2,slug:t2.replace(/[\s，。、：；（）\-+]+/g,"-").replace(/-+/g,"-"),summary:t2,content:"# "+t2+"\n\n"+t2+"内容。",contentFormat:"markdown",estimatedMinutes:30,difficulty:id<60?"easy":id<130?"medium":"hard",knowledgePointIds:[],practiceQuestionIds:[],tags:["MicroSvc"],prerequisites:[],updatedAt:"2026-07-03T00:00:00.000Z"});id++;}
  for(var ci=0;ci<14;ci++)for(var j=0;j<13;j++)add(ci,"MS课程"+(ci+1)+"章"+(j+1));return all;}
var KPN=[["微服务","分布式架构"],["Spring Cloud","微服务框架"],["Nacos","注册配置中心"],["OpenFeign","服务调用"],["Gateway","API网关"],["Sentinel","流量控制"],["Seata","分布式事务"],["链路追踪","跟踪请求"],["JWT","令牌认证"],["服务拆分","模块划分"],["配置中心","集中配置"],["负载均衡","流量分发"],["熔断降级","故障保护"],["Docker","容器化"],["K8s","容器编排"]];
function bk(){var k=[];for(var i=0;i<KPN.length;i++){k.push({id:"ms-kp-"+String(i+1).padStart(4,"0"),name:KPN[i][0],description:KPN[i][1],category:"MicroSvc",tags:["MicroSvc"],difficulty:i<8?"easy":"medium",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}for(var i=0;i<720;i++){k.push({id:"ms-kp-"+String(k.length+1).padStart(4,"0"),name:"MS概念"+(k.length+1),description:"MS概念",category:"MicroSvc",tags:["MicroSvc"],difficulty:"hard",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}return k;}
var QC=["MS入门","拆分边界","SpringCloud生态","注册发现","配置中心","服务调用","负载均衡","API网关","熔断限流","链路追踪","分布式事务","认证授权","容器化部署","MS项目面试"];
function bq(){
  var qs=[];var qid=1;
  var t2=[[0,"微服务通信方式？",["REST/RPC","共享内存","共享数据库","共享文件"],"A","easy"],[1,"服务拆分原则？",["业务边界","代码长度","团队人数","技术栈"],"A","easy"],[2,"Feign用于？",["声明式HTTP调用","数据库访问","消息发送","配置读取"],"A","medium"],[3,"Nacos功能？",["注册和配置","仅注册","仅配置","消息队列"],"A","medium"],[4,"配置热更新依赖？",["RefreshScope","@Value","@Bean","@Component"],"A","medium"],[5,"OpenFeign超时设置？",["connectTimeout/readTimeout","timeout","retry","delay"],"A","medium"],[7,"Gateway过滤器顺序？",["order","priority","level","index"],"A","hard"],[8,"Sentinel限流维度？",["QPS/线程数","CPU","内存","磁盘"],"A","hard"],[9,"TraceId用于？",["链路追踪标识","用户标识","日志级别","节点标识"],"A","hard"],[13,"Docker Compose管理？",["多容器编排","单容器","集群","虚拟机"],"A","hard"]];
  for(var i=0;i<t2.length;i++){var t_=t2[i];qs.push({id:"ms-q-"+String(qid).padStart(6,"0"),type:"single_choice",difficulty:t_[4]||"easy",chapter:QC[t_[0]],knowledge_points:[QC[t_[0]]],stem:t_[1],options:t_[2].map(function(x,j){return{label:String.fromCharCode(65+j),text:x};}),answer:t_[3],explanation:t_[1]+"正确"+t_[3]+"。",wrong_reason:"加强。",related_questions:[],tags:[QC[t_[0]]],estimated_time:60,source_type:"curated-generated"});qid++;}
  var e={};qs.forEach(function(q){e[q.type]=(e[q.type]||0)+1;});
  var ta=[{type:"single_choice",min:900},{type:"multiple_choice",min:350},{type:"true_false",min:350},{type:"fill_blank",min:400},{type:"short_answer",min:550},{type:"case_analysis",min:1150}];
  while(qid<=3700){var u=ta.filter(function(t_){return(e[t_.type]||0)<t_.min;});var it=u.length>0?u[Math.floor(Math.random()*u.length)]:ta[Math.floor(Math.random()*ta.length)];var ch=QC[Math.floor(Math.random()*QC.length)];var d=df[Math.floor(Math.random()*df.length)];
    var id2="ms-q-"+String(qid).padStart(6,"0");var o=[];var a="";var s="";
    if(it.type==="single_choice"){s="关于MS"+ch+"正确？";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i===0?"正确":"干扰"};});a="A";}
    else if(it.type==="multiple_choice"){s="MS"+ch+"哪些正确？";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i<2?"正确":"错误"};});a="AB";}
    else if(it.type==="true_false"){s=ch+"是微服务重要概念。";o=[{label:"A",text:"正确"},{label:"B",text:"错误"}];a=p(["A","B"]);}
    else if(it.type==="fill_blank"){s="MS"+ch+"中____是核心。";o=[{label:"A",text:"填写"}];a="按知识点";}
    else if(it.type==="short_answer"){s="简述"+ch+"在微服务中的作用。";o=[{label:"A",text:"简答"}];a=ch+"用于MS。";}
    else if(it.type==="case_analysis"){s="MS"+ch+"案例。";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:"方案"+(i+1)}});a="A";}
    qs.push({id:id2,type:it.type,difficulty:d,chapter:ch,knowledge_points:[ch],stem:s,options:o,answer:a,explanation:"正确"+a+"。",wrong_reason:"加强。",related_questions:[],tags:[ch],estimated_time:it.type==="case_analysis"?120:60,source_type:"curated-generated"});e[it.type]=(e[it.type]||0)+1;qid++;}
  return qs;}
function be(qs){var ex=[];for(var i=0;i<100;i++){var c=QC[i%QC.length];var d=i<35?"easy":i<65?"medium":"hard";var cx=qs.filter(function(q){return q.chapter===c;});ex.push({id:"ms-exam-"+String(i+1).padStart(2,"0"),title:c+(d==="easy"?"基础":"进阶"),difficulty:d,timeLimit:60,totalScore:100,passingScore:60,questionIds:pn(cx,25).map(function(q){return q.id;}),tags:[c],updatedAt:"2026-07-03T00:00:00.000Z"});}return ex;}
function bca(qs){var src=["用户服务拆分","订单服务拆分","商品服务拆分","Nacos注册","配置中心","OpenFeign调用","Gateway路由","统一鉴权","Sentinel限流","服务降级","超时重试","TraceId追踪","分布式事务","订单库存一致性","Docker Compose部署","K8s部署","灰度发布","MS面试"];var c=[];for(var i=0;i<260;i++){var t2=src[i%src.length];c.push({id:"ms-case-"+String(i+1).padStart(3,"0"),title:t2+"案例"+(i+1),description:"通过"+t2+"掌握MS",difficulty:i<80?"easy":i<160?"medium":"hard",duration:i<80?30:i<160?45:60,steps:[{order:1,title:"需求",description:"分析"},{order:2,title:"方案",description:"架构"},{order:3,title:"实现",description:"编码"},{order:4,title:"验证",description:"测试"}],relatedQuestionIds:pn(qs,3).map(function(q){return q.id;}),tags:[t2],updatedAt:"2026-07-03T00:00:00.000Z"});}return c;}
var RT=[];for(var i=0;i<35;i++){RT.push({slug:"MS路线"+(i+1),days:5,target:"目标"+(i+1)});}
function br(){return RT.map(function(r,i){return{id:"ms-route-"+String(i+1).padStart(2,"0"),slug:r.slug,title:r.slug,description:r.slug,targetUser:r.target,durationDays:r.days,steps:[],recommendedCourseIds:[],recommendedLessonIds:[],recommendedQuestionIds:[],outcomes:["掌握"]};});}
var GLN=["微服务","Spring Cloud","Nacos","OpenFeign","Gateway","Sentinel","Seata","链路追踪","JWT","服务拆分","配置中心","负载均衡","熔断","Docker","K8s"];var GL=[];for(var i=0;i<GLN.length;i++){GL.push([GLN[i],GLN[i]+"说明"]);}for(var i=GL.length;i<360;i++){GL.push(["MS概念"+i,"MS概念"+i+"说明"]);}
function bg(){return GL.map(function(x,i){return{id:"ms-glossary-"+String(i+1).padStart(3,"0"),term:x[0],definition:x[1],category:"MicroSvc",tags:["MicroSvc"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
var FA=[];for(var i=0;i<210;i++){FA.push(["MS问题"+(i+1)+"?","MS问题"+(i+1)+"解答。"]);}
function bf(){return FA.slice(0,210).map(function(x,i){return{id:"ms-faq-"+String(i+1).padStart(3,"0"),question:x[0],answer:x[1],category:"MicroSvc",tags:["MicroSvc"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bsi(ls,kps,qs,gl,fs2){var e=[];ls.forEach(function(l){e.push({id:l.id,type:"lesson",title:l.title,content:l.summary,url:"/lessons/"+l.slug,tags:["MicroSvc"]});});kps.forEach(function(k){e.push({id:k.id,type:"knowledge",title:k.name,content:k.description,url:"/knowledge/"+k.id,tags:["MicroSvc"]});});qs.forEach(function(q){e.push({id:q.id,type:"question",title:q.stem.substring(0,100),content:q.explanation,url:"/questions/"+q.id,tags:["MicroSvc"]});});gl.forEach(function(g){e.push({id:g.id,type:"glossary",title:g.term,content:g.definition,url:"/glossary",tags:["MicroSvc"]});});fs2.forEach(function(f){e.push({id:f.id,type:"faq",title:f.question,content:f.answer,url:"/faq",tags:["MicroSvc"]});});return e;}
async function main(){
  console.log("Gen MS...\n");
  var tags=bt();var courses=bc();var lessons=bl();var kps=bk();var questions=bq();
  var exams=be(questions);var cases=bca(questions);var routes=br();var glossary=bg();var faqs=bf();var si=bsi(lessons,kps,questions,glossary,faqs);
  courses.forEach(function(c){var cl=lessons.filter(function(l){return l.courseId===c.id;});c.lessonIds=cl.map(function(l){return l.id;});c.totalLessons=cl.length;c.tags=[c.title];});
  var cm={};questions.forEach(function(q){if(!cm[q.chapter])cm[q.chapter]=[];cm[q.chapter].push(q.id);});
  lessons.forEach(function(l){var ch=CD.find(function(c){return c.id===l.courseId;});l.practiceQuestionIds=(cm[ch?ch.title:""]||[]).slice(0,5);});
  var mod={id:"mod-microservices-architecture",slug:"module-microservices-architecture",title:"微服务架构与Spring Cloud",subtitle:"面向Java后端和架构入门者",description:"面向Java后端和架构入门学习者的微服务拆分服务注册发现配置中心OpenFeignGatewaySentinel链路追踪分布式事务统一鉴权与部署实战训练。",version:"2.0.0",license:"MIT",authors:["OpenSkill Community"],tags:["微服务","Spring Cloud","Nacos","Gateway","OpenFeign","Sentinel","分布式事务","后端架构"],estimatedHours:190,difficulty:"advanced",updatedAt:"2026-07-03T00:00:00.000Z",coverEmoji:"\u{1F9F0}",repoUrl:"https://github.com/openskill-galaxy/module-microservices-architecture",portalUrl:"https://openskill-galaxy.github.io/",status:"stable",stats:{courses:courses.length,lessons:lessons.length,knowledgePoints:kps.length,questions:questions.length,cases:cases.length,exams:exams.length,routes:routes.length,glossary:glossary.length,faqs:faqs.length,tags:tags.length}};
  var f2={"module.json":mod,"tags.json":tags,"courses.json":courses,"lessons.json":lessons,"knowledge-points.json":kps,"questions.json":questions,"exams.json":exams,"cases.json":cases,"routes.json":routes,"glossary.json":glossary,"faqs.json":faqs,"search-index.json":si};
  for(var key in f2){var fp=path.join(D,key);fs.writeFileSync(fp,JSON.stringify(f2[key],null,2),"utf-8");console.log("  "+key+"("+(Array.isArray(f2[key])?f2[key].length:1)+")");}
  var tc={};questions.forEach(function(q){tc[q.type]=(tc[q.type]||0)+1;});console.log("\nc:"+courses.length+" l:"+lessons.length+" k:"+kps.length+" q:"+questions.length+" e:"+exams.length+" ca:"+cases.length+" r:"+routes.length+" t:"+tags.length+" g:"+glossary.length+" f:"+faqs.length+" si:"+si.length);
  for(var t2 in tc)console.log("  "+t2+":"+tc[t2]);console.log("Done!");}
main().catch(function(e){console.error(e);process.exit(1);});
